# Generated by Django 2.1.4 on 2018-12-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20181215_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='user_id',
            field=models.CharField(default='value', max_length=100),
        ),
    ]
